language: objective-c
osx_image: xcode8.3

if: branch = master

rvm:
  - '2.2'

before_install:
  - chmod a+x ./Scripts/install.sh
  - chmod a+x ./Scripts/build.sh

install:
  - ./Scripts/install.sh

script:
  - ./Scripts/build.sh