jobs:
  include:
    - stage: deploy
      language: objective-c
      osx_image: xcode8.3
      if: branch = master
      rvm:
        - '2.2'

      before_install:
        - chmod a+x ./.Scripts/build.sh
        - chmod a+x ./.Scripts/install.sh
        - chmod a+x ./.Scripts/install-butler.sh
        
      install:
        - ./.Scripts/install.sh
        - ./.Scripts/install-butler.sh
      script:
        - ./.Scripts/build.sh
        - ./butler push /Build/linux lucascosta/puzzlebattle:linux-stable
        - ./butler push /Build/osx lucascosta/puzzlebattle:osx-stable
        - ./butler push /Build/windows lucascosta/puzzlebattle:win-stable
